server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-connections:

spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/taotao
    username: root
    password: Lbr@170214
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.firstspringboot.common.vo
  mapperLocations: classpath:mapper/*.xml

